--[[
file: runme.lua
This file illustrates yaml-cpp C++ library lua interface generated by SWIG, 
using an helper class : yaml_lua.h

* References
https://www.swig.org/Doc1.3/SWIG.html
https://www.swig.org/Doc1.3/SWIGPlus.html
https://github.com/michaelbaisch/ofxYAML/blob/master/src/ofxYAML.h
]]--

---- importing ----
if string.sub(_VERSION,1,7)=='Lua 5.0' then
	-- lua5.0 doesn't have a nice way to do this
	lib=loadlib('yaml_lua.dll','luaopen_example') or loadlib('yaml_lua.so','luaopen_example')
	assert(lib)()
else
	-- lua 5.1 does
	require('yaml_lua')
end

yaml = yaml_lua.yaml()
config = yaml:load("config.yaml")
configMap = yaml:asMap(config)
--[[
---
  pid: '/home/www/pids/thin.pid'
  wait: 30
  port: 3000
  timeout: 15
  servers: 2
  require: []
  dbg-mode: false
]]--

print ("--- config: ")
print ("pid: " .. configMap["pid"])
print ("wait: " .. configMap["wait"])
print ("port: " .. configMap["port"])
print ("timeout: " .. configMap["timeout"])
print ("servers: " .. configMap["servers"])
print ("require: " .. configMap["require"])
print ("dbg-mode: " .. configMap["dbg-mode"])


cookeLens = yaml:load("cooke-lens.yaml")
cookeLensMap = yaml:asMap(cookeLens)
print ("--- cooke-lens: ")
print ("RecordType: " .. cookeLensMap["RecordType"])
