-- file: runme.lua
-- This file illustrates XClip C++ library lua interface generated by SWIG.

---- importing ----
if string.sub(_VERSION,1,7)=='Lua 5.0' then
	-- lua5.0 doesn't have a nice way to do this
	lib=loadlib('yaml-lua.dll','luaopen_example') or loadlib('yaml-lua.so','luaopen_example')
	assert(lib)()
else
	-- lua 5.1 does
	require('yaml-lua')
end

--[[
your lua code...
Check the yaml-cpp parser examples

Check the swig docs
https://www.swig.org/Doc1.3/SWIG.html
https://www.swig.org/Doc1.3/SWIGPlus.html

Check this simple yaml-cpp wrapper from an openframeworks addon
https://github.com/michaelbaisch/ofxYAML/blob/master/src/ofxYAML.h
]]--

